// Signaling organ type definitions
// Defines the event envelope for inter-node communication
// Constants are imported from DNA (the source of truth) and re-exported

// Re-export DNA constants for consumers
export { SIGNAL_EVENT_TYPES } from "../../dna.js";

// Import for local type derivations
import { SIGNAL_EVENT_TYPES } from "../../dna.js";

// Type derivation from DNA constant
export type SignalEventType = (typeof SIGNAL_EVENT_TYPES)[number];

/**
 * A SignalEvent is the minimal envelope for inter-node communication.
 *
 * Events are append-only and idempotent (same eventId = same event).
 * They enable federation without sharing internal state.
 */
export interface SignalEvent {
  /** Unique identifier for this event (used for idempotency) */
  eventId: string;
  /** The source node that emitted this event */
  nodeId: string;
  /** The type of signal: intent, status, or completion */
  type: SignalEventType;
  /** Event-specific payload (shape depends on type) */
  payload: unknown;
  /** ISO-8601 timestamp when event was created */
  timestamp: string;
}

/**
 * Parameters for creating a new SignalEvent.
 * The eventId and timestamp are typically generated by the caller.
 */
export interface CreateSignalEventParams {
  eventId: string;
  nodeId: string;
  type: SignalEventType;
  payload: unknown;
  timestamp: string;
}
